### ISSUE TITLE
Basic howto

### ISSUE THREAD

**Issue by stevenbird** [langtech/langtech.github.com#1]
Create initial basic howto for Aikuma including screenshots. It should presume no prior experience with Aikuma.

**Comment by LaurenGawne** [comment]
Currently being build at http://lp20.org/aikuma/howto.html

Sections added for main page, adding users and settings page. 
Need to improve image alignment and image size.

**Comment by stevenbird** [comment]
The alignment problem is addressed in issue #3.

**Comment by stevenbird** [comment]
Looking good! Here's some editorial feedback:
- "add at least speaker" (missing "a")
- xrefs to other sections of the howto could be hyperlinks (e.g. replace `create a new user (the process for this is discussed in the Users section below)` with `[create a new user](xref)`.
- "Pressing the large red cross at the bottom of the screen will save the recording to your collection" should be talking about the green tick!
- thumb commentary - this works best with the phone held sideways; note also that multiple presses of the green play button allow you to listen to the same segment over again
- "With most phones you will be given the chance to accept the photo" - not sure why this is "with most phones" (should be common across all phones)

**Comment by LaurenGawne** [comment]
- Current version now contains instructions on almost all aspects
- Images all current for version 1.0.0-beta.13

Still to do:
- Add pages for viewing recordings with commentary attached and navigating these
- Figure out how to use markdown for cross-referencing correctly
- Final Proofread
- Make live

**Comment by floere** [comment]
Awesome! (Isn't it already live, though?)

**Comment by LaurenGawne** [comment]
@floere yes, sorry, it is live at the moment, but there's no link to the rest of the site until I hit the pull request. I'll do that after the final additions tomorrow. Any other feedback is welcome at any time!

**Comment by floere** [comment]
@LaurenGawne Got it :)

**Comment by LaurenGawne** [comment]
All content is now in place for Aikuma How To page. The only things left to do are:
1. Final proofread (all feedback welcome)
2. figure out how to make internal links work. Tried what I can find on the web, but nothing works. Any suggestions?

**Comment by LaurenGawne** [comment]
Have now figured out how to create successful internal links using a bit of html in the document to create named anchors (  <a name="Foo"></a> )

Just doing that, and final trial use, and I'll hit the pull request later today

**Comment by floere** [comment]
Nice! You beat me to it :)

**Comment by LaurenGawne** [comment]
Sorry for the confusing flurry of work this afternoon. I added all the other links and did some final proofreading. The page isn't working though. I've doubled checked everything and the only thing I can come up with is that somehow the html inserted lower down for the anchors other than the main one isn't being parsed properly. If anyone has any suggestions that would be great!

**Comment by LaurenGawne** [comment]
Fixed from previous comment (I had bad brackets). I'm going to activate the pull request ( #4 ) and link it to the rest of the site now. 

Any/all feedback welcome at any time.

**Comment by stevenbird** [comment]
This is great. I'll close this now, and we can process feedback and updates via a new issue. Thanks!
